### PR TITLE
Generate numbered instances

### PR DESCRIPTION
**Pull request by mciantyre**
The PR updates the RAL API with uniquely-numbered `Instance` types. Before this PR, all `LPUARTx` instances shared the same `Instance` type. As of this PR, all `LPUARTx` instances are unique over `x`. To make that a bit more concrete, here's what the types now look like

```rust
use imxrt_ral::lpuart;

// Before
let _: lpuart::Instance = lpuart::LPUART4::take().unwrap();

// After
use typenum::U4;
let _: lpuart::Instance<U4> = lpuart::LPUART4::take().unwrap();
```

The implementation was inspired by the [async HAL's `instance` module](https://github.com/imxrt-rs/imxrt-async-hal/blob/be400de3159e627061c7a131439e7e769201175c/src/instance.rs#L1). The type-level constants pair well with the `imxrt-iomuxc` API, and it allows a HAL to statically ensure that a peripheral instance and IOMUXC pins match.

This change will affect peripherals with multiple instances, like GPIO, LPUART, LPSPI, LPI2C, etc. It also affects peripherals that only have a single instance. The decision to change all instances matters when writing consistent APIs for cross-chip support (a single USB instance on a 1021, and multiple USB instances on a 1062, should have the same `Instance<N>` appearance). The code generation inlines a default "single instance" identifier so that these types appear similar, and hopefully minimize breakages.

I needed SVD patches to support code generation. The patches change the names of the first FLEXSPI and ENET instances. It also removes the '1' from `ADC1` for 1011 and 1015 chips, resulting in consistent `adc` module names across all chips (see #9 for a similar change).

TODO:

- [x] fix codegen for the `"rtic"` feature
- [x] consider exposing the `typenum` constants from the RAL API, so that users don't have to separately depend on `typenum`.
- [x] provide recommendations and examples on how users might bypass the strongly-numbered types.
- [x] update CHANGELOG
- [x] breaking version bump

### CODE REVIEW

**Comment by mciantyre** [comment]
I integrated this new API in both the `imxrt-ccm` crate, and the `imxrt-async-hal` crate. It's sufficient to replace the async HAL's `instance` module.

Keeping in draft while I mull over the API, and play with it some more in other imxrt-rs crates. Feel free to leave additional thoughts!

**Comment by teburd** [comment]
I like the idea of each one having its own numerically appended type alias, this shouldn't break anything?

**Comment by mciantyre** [comment]
Would that type alias look like

```rust
pub type LPUART4 = Instance<U4>;
```

or, am I misinterpreting the type alias idea?

If we're going for the above, we would need to put the instance aliases in a different module, since the alias conflicts with the `pub mod LPUART4` module.

**Comment by teburd** [comment]
Yes, that is what I was thinking

**Comment by mciantyre** [comment]
Latest commit changes this decision:

> Singular peripheral instances are not generalized over a typenum constant, so those instances look the same.

See rational in the latest commit, and in the usage docs. Updated top-level comment to describe the change.

**Comment by mciantyre** [comment]
Closing out this experiment. I'm breaking out the supporting commits into other PRs. I have a different, const generic-based approach I'll share for feedback.

**Pull request closed without merging**
