### PR TITLE
Generate imxrt-ral using raltool

### PR DESCRIPTION
**Pull request by mciantyre**
The PR follows #29 and generates `imxrt-ral` using `raltool`. The first and last commits remove and add all of the `imxrt-ral` sources, respectively. The remaining commits

- add support for multi-core i.MX RT 1176 MCUs (#26).
- consolidate register blocks in terms of `raltool` transformations and SVD patches.
- update documentation, project infrastructure, examples, etc.

I used this `imxrt-ral` throughout imxrt-rs/imxrt-hal#121 development.

Consult the contributing documentation and CI job definitions to understand the new ways to generate and test `imxrt-ral`. One notable change: we're now using the Rust-based `svdtools` program, instead of the Python equivalent, for SVD patching. This means we don't need a Python environment to generate `imxrt-ral`.

### CODE REVIEW

**Comment by teburd** [comment]
I'm not going to look at the generated diff here, and frankly I wonder since this is now a rust tool in itself if it couldn't be generated at build time to avoid needing to keep it in git. Deleting 1mloc sounds nice, recalling why it was added before I think it was for docs and avoiding needing python tooling installed to build it. Is that still the case?

The ral tool itself being in cargo, and being based on chiptool is a win hands down. :+1: from me.

**Comment by mciantyre** [comment]
Yea there's way too much to review here. Beyond testing it in the HAL, I did spot checks by eye, and I have [small tests](https://github.com/mciantyre/imxrt-ral/blob/0cd4ca43d6996ef4c723ced98cc75e84ef7574aa/tests/ccm_1170.rs#L1) to make sure `raltool` is generating sane register blocks. We can expand these tests when we find issues.

---

Having all the Rust code in git means we can use the repository as [a git dependency](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#specifying-dependencies-from-git-repositories), which helps when developing across the repos. But now that all tooling is in Rust, you're right; we could reliably generate _everything_ at build time.

Some thoughts and estimates, keeping the pipeline in mind:

```
Unpatched SVDs -> [svdtools] -> Patched SVDs -> [raltool] -> imxrt-ral
```

- `svdtools` is published as both a library and a binary, so we could use the library as an `imxrt-ral` build dependency.
  - Users will spend time building `svdtools` when building `imxrt-ral` from scratch. Not estimating a build time right now.
  - On my system, I can patch all SVDs in parallel in 1.7 seconds. Takes 7.4 seconds to sequentially patch. I'm always using an optimized `svdtools` binary.
- `raltool` would need to be published and available as an `imxrt-ral` build dependency.
  - Users spend time building `raltool`, too. ~20 seconds best-case for me. Caveat: could reduce this time by removing dependencies.
  - I can generate `imxrt-ral` in 5.5 seconds with an optimized `raltool`, and 40 seconds with an unoptimized `raltool` (previously measured 80 seconds before removing a slow debug assertion).

From my understanding, [Cargo will not apply optimizations to build dependencies](https://doc.rust-lang.org/cargo/reference/profiles.html#build-dependencies) unless the user provides an override. That's why I'm considering the unoptimized `raltool` codegen time. If any `imxrt-ral` user doesn't specify that override, their build-from-scratch time might be dominated by unoptimized SVD patching and `raltool` codegen. We could teach users about this configuration.

**Comment by teburd** [comment]
> Yea there's way too much to review here. Beyond testing it in the HAL, I did spot checks by eye, and I have [small tests](https://github.com/mciantyre/imxrt-ral/blob/0cd4ca43d6996ef4c723ced98cc75e84ef7574aa/tests/ccm_1170.rs#L1) to make sure `raltool` is generating sane register blocks. We can expand these tests when we find issues.
> 
> Having all the Rust code in git means we can use the repository as [a git dependency](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#specifying-dependencies-from-git-repositories), which helps when developing across the repos. But now that all tooling is in Rust, you're right; we could reliably generate _everything_ at build time.
> 
> Some thoughts and estimates, keeping the pipeline in mind:
> 
> ```
> Unpatched SVDs -> [svdtools] -> Patched SVDs -> [raltool] -> imxrt-ral
> ```
> 
>  * `svdtools` is published as both a library and a binary, so we could use the library as an `imxrt-ral` build dependency.
>   
>   * Users will spend time building `svdtools` when building `imxrt-ral` from scratch. Not estimating a build time right now.
>   * On my system, I can patch all SVDs in parallel in 1.7 seconds. Takes 7.4 seconds to sequentially patch. I'm always using an optimized `svdtools` binary.
> * `raltool` would need to be published and available as an `imxrt-ral` build dependency.
>   
>   * Users spend time building `raltool`, too. ~20 seconds best-case for me. Caveat: could reduce this time by removing dependencies.
>   * I can generate `imxrt-ral` in 5.5 seconds with an optimized `raltool`, and 40 seconds with an unoptimized `raltool` (previously measured 80 seconds before removing a slow debug assertion).
> 
> From my understanding, [Cargo will not apply optimizations to build dependencies](https://doc.rust-lang.org/cargo/reference/profiles.html#build-dependencies) unless the user provides an override. That's why I'm considering the unoptimized `raltool` codegen time. If any `imxrt-ral` user doesn't specify that override, their build-from-scratch time might be dominated by unoptimized SVD patching and `raltool` codegen. We could teach users about this configuration.

I think it’s your decision. That doesn’t sound too bad taking ~60s to generate and build the ral

**Comment by mciantyre** [comment]
When `imxrt-rs` code is already on disk (as part of a package / repo), I measured [9 seconds build](https://github.com/imxrt-rs/imxrt-ral/tree/master/raltool#benchmarks) for `cargo build --features=imxrt1062`. Assuming these are all reasonable estimates, I don't think we should ask users to wait ~6x longer for a build to complete.

**Comment by teburd** [comment]
Then there’s the answer!

**Pull request merged**
