### PR TITLE
Derive SAI blocks for 1176 from SAI1

### PR DESCRIPTION
**Pull request by SpinFast**
All SAI instances can derive their register blocks from SAI1. While not
  every instance has multiple tx/rx lines and fifos the register layout
  can be reused for all SAI instances. The mcux sdk actually does this
  by casting the instance address to I2S_Type* which is a common struct
  with a common register layout.

### CODE REVIEW

**Comment by mciantyre** [comment]
When I locally generate the RAL, I don't see any changes to the Rust code. There's a CI job that confirms this, too. If the SVDs were the root cause, I would have expected there to be a change in the Rust source code as of these SVD updates.

I'm not sure this will fix the issue. Could you check my notes here? All links are as of the 0.5.3 tag.

The 1176 (CM7) has two different SAI modules: `sai`, and `sai1`.

https://github.com/imxrt-rs/imxrt-ral/blob/bb0088d5b35b5575d5e228291f9fd03586c5322e/src/imxrt1176_cm7.rs#L4542-L4629

The `sai`-without-`1` **does not** have an array for TDR. It's just `TDR0`.

https://github.com/imxrt-rs/imxrt-ral/blob/bb0088d5b35b5575d5e228291f9fd03586c5322e/src/blocks/imxrt1176_cm4/sai.rs#L21

The `sai1` **does** have an array for TDR.

https://github.com/imxrt-rs/imxrt-ral/blob/bb0088d5b35b5575d5e228291f9fd03586c5322e/src/blocks/imxrt1176_cm4/sai1.rs#L21

**Comment by mciantyre** [comment]
Here's a few "don't want to deal with this" ideas that would be OK with me.

Within the **HAL**, and when the 1170 feature is active, remap `ral::sai1` to `ral::sai`. That might allow the driver to build for 1170 MCUs, but it only supports the sole multi-channel SAI instance. We could consider some tricks; when the 1170 build is active, provide an `unsafe` constructor to go from single-channel SAI instances to multi-channel SAI instances. The user promises "I won't touch those extra channels." We pointer cast register blocks inside the HAL. Not great as is, but could be a start for some kind of type- or runtime-safer approach.

Within the HAL, don't export SAI as a common driver. Pick your favorite MCU families and export it when that feature is active.

**Comment by SpinFast** [comment]
I'd like to fix it, 1176 would be cool to have at some point perhaps.

I'll see what I can do to correct the svd with patching methods

**Comment by SpinFast** [comment]
From what I can tell other parts provide a single block that has registers as arrays regardless of whether the instance has the full set of channels. That works for me. I tried patching it but svdtools is I don't think as helpful here as I would like. I'll consider the other options tomorrow.

**Comment by SpinFast** [comment]
The svdtools patch now generates ral stuff that looks a lot closer to the other parts as the registerblock gets reused for all instances

**Review by mciantyre — APPROVED** [review]
Thanks for digging into this. I'll include this in a future breaking release (0.6) of imxrt-ral.

I'm pondering ways to hack something like this within the 0.5 series, but I haven't seen the path yet. If we figured this out, we could release the HAL's SAI driver within imxrt-hal 0.5 series and still fully support the 1170. Of course, we could always release the SAI driver in the HAL's 0.5 series without immediately supporting all MCUs.

It's also OK to update the HAL's dependency on the RAL to realize this change for SAI development.

**Pull request merged**
